steps: # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$_SERVICE_NAME",
        "-f",
        "Dockerfile-onTriggerFunction",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$_SERVICE_NAME"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
      - "--concurrency"
      - "100"
      - "--min-instances"
      - "2"
      - "--max-instances"
      - "10"
images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME"
substitutions:
  _SERVICE_NAME: macmedics
  _REGION: us-central1
